### ISSUE TITLE
Authomatic Usecases

### ISSUE THREAD

**Issue by peterhudec** [authomatic/authomatic#1]
I would love to hear from you in comments below whether you use **Authomatic**, how you use it, why you use it or why you don't.

**Comment by lugearma** [comment]
I have this error message:
´´´
Failed to obtain request token from https://api.twitter.com/oauth/request_token! HTTP status code: 401    content: Desktop applications only support the oauth_callback value 'oob' /oauth/request_token?oauth_nonce=4c7b99721f46a774edc558c6df&oauth_timestamp=1427743083&oauth_consumer_key=5ROubSCwMYsCLjHd4rzlYpMjt&oauth_signature_method=HMAC-SHA1&oauth_version=1.0&oauth_signature=k7Un015dyBljIfh4oTdI1%2BF132o%3D&oauth_callback=http%3A%2F%2F127.0.0.1%3A8000%2Fauth%2Ftwitter
´´´

**Comment by peterhudec** [comment]
Please use [stackoverflow](http://stackoverflow.com/) to ask questions.
Use issues only for bug reports and feature requests.
