### ISSUE TITLE
Authomatic.login returns 'None' when I add additional arguments to the url (eg. .../login/fb?next=test)

### ISSUE THREAD

**Issue by seb5s** [authomatic/authomatic#108]
Hi,

I'm having trouble with the Authomatic.login method. I have downloaded the files from the Flask tutorial at:
http://peterhudec.github.io/authomatic/examples/flask-simple.html

Everything is working fine when I go to: 
mydomain.com/login/fb

However, if I try to pass additional arguments, the login method returns None. 
E.g mydomain.com/login/fb?next=test returns None

Does anyone know a solution to this problem?

/Sebastian

**Comment by ParthGandhi** [comment]
Look at:
https://github.com/peterhudec/authomatic/issues/63
https://github.com/peterhudec/authomatic/issues/70
