### ISSUE TITLE
unable to get logged in user via google

### ISSUE THREAD

**Issue by avitavdi** [authomatic/authomatic#110]
Im trying to create handler that will return the logged in google user, here is my code:

``` python
CONFIG = {

    'google': {
        'class_': 'authomatic.providers.oauth2.Google',
        'id': authomatic.provider_id(),  # returns 2
        'consumer_key': 'XXXXXX',
        'consumer_secret': 'XXXXXX',
        'scope': ['https://www.googleapis.com/auth/userinfo.profile',
                  'https://www.googleapis.com/auth/userinfo.email']
    }
}

class Login(webapp2.RequestHandler):
    def any(self, provider_name):
        result = authomatic.login(Webapp2Adapter(self), 'google')
        if result:
            if result.user:
                result.user.update()
                self.response.write('<h1>Hi {0}</h1>'.format(result.user.name))

authomatic = Authomatic(config=CONFIG, secret='sadfasdfsgfr')
Login(webapp2.get_request())
```

im getting AssertionError: Request global variable is not set.

The documentation in the website is quite lacking, the examples require configuration that is not mentioned.

My goal is to get the email address of the current google user, i've been looking at https://developers.google.com/oauthplayground/ and tried to emulate the same flow in python but was unsuccessful.
Can you please help out?

Thanks!

**Comment by jensens** [comment]
you need to enable the google+ api in order to get the data
