### ISSUE TITLE
Instagram support

### ISSUE THREAD

**Issue by nicocanali** [authomatic/authomatic#111]
Is there any plan to add Instagram support?

**Comment by peterhudec** [comment]
Deffinitely.

Actually I wanted to include it right from the beginning, but I could not register on Instagram because I didn't have a smartphone.

**Comment by gutomaia** [comment]
I'm also interested in this feature!

**Comment by mrichar1** [comment]
After several years of inactivity, `authomatic` is now under community management, and we have just released a new stable version (`1.0.0`).

We are now reviewing all issues and PRs and hoping to begin work to solve as many of these as possible.

We are keen to find out which issues still apply, and which PRs are still required/are likely to merge cleanly into the current code. We are aiming to review them all, but any help with prioritisation would be very useful!

If you are still interested in having this issue/PR resolved, or are able to help us work on it, please reply to this message. That way we know which issues are most important to the community.
