### ISSUE TITLE
Facebook API 2.4

### ISSUE THREAD

**Issue by DeBlinx** [authomatic/authomatic#112]
Hello, 
i created a new Facebook app with API Version 2.4. Now i can not access the E-Mail nor any other information except the public profile of the logged in user. I granted facebook the permission but the email is NONE. If i change the app ID and the app secret to an app with API Version 2.0 i get all desired information.

**Comment by bubanoid** [comment]
I have the same problem. Facebook sets the latest API v.2.4 to every new application, but this API is not supported by current version of authomatic. The problem is critical as none of new apps can introduce Facebook authorization in its functionality until this issue is resolved.

**Comment by mardix** [comment]
Same issue right here too :(

**Comment by koorukuroo** [comment]
I have also same problem. I thought it's about permission in API page. But it's wrong... I don't know.. ;(

**Comment by Kylotan** [comment]
I can't even log in with my app - nowhere on my Facebook app page appears to offer me a consumer key/secret pair so it's not clear what I would use to even try this.

**Comment by miohtama** [comment]
Here is a quick fix for `Facebook.user_info_url`:

    class Facebook(OAuth2):
        """
        Facebook |oauth2| provider.
        
        * Dashboard: https://developers.facebook.com/apps
        * Docs: http://developers.facebook.com/docs/howtos/login/server-side-login/
        * API reference: http://developers.facebook.com/docs/reference/api/
        * API explorer: http://developers.facebook.com/tools/explorer

        Supported :class:`.User` properties:

        * city
        * country
        * email
        * first_name
        * gender
        * id
        * last_name
        * link
        * locale
        * name
        * picture
        * timezone
        * username

        Unsupported :class:`.User` properties:

        * birth_date
        * nickname
        * phone
        * postal_code

        """
        
        user_authorization_url = 'https://www.facebook.com/dialog/oauth'
        access_token_url = 'https://graph.facebook.com/oauth/access_token'
        
        # See all available fields https://developers.facebook.com/docs/graph-api/reference/user
        user_info_url = 'https://graph.facebook.com/me?fields=id,email,name,first_name,last_name,address,gender,hometown,link,timezone,verified,website,locale,languages'

More info:

* https://developers.facebook.com/blog/post/2015/07/08/graph-api-v2.4/

* https://github.com/mkdynamic/omniauth-facebook/pull/209

**Comment by miohtama** [comment]
Also following works:

    def capture_social_media_user(self, request, result) -> IUserClass:
        """Extract social media information from the login in order to associate the user account."""
        assert not result.error

        # Facebook specific Authomatic call to fetch more user data from the Facebook provider
        result.user.provider.user_info_url = 'https://graph.facebook.com/me?fields=id,email,name,first_name,last_name,address,gender,hometown,link,timezone,verified,website,locale,languages'
        result.user.update()

        # Make user Facebook user looks somewhat legit
        assert result.user.credentials
        assert result.user.id

        if not result.user.email:
            # We cannot login if the Facebook doesnt' give us email as we use it for the user mapping
            # This can also happen when you have not configured Facebook app properly in the developers.facebook.com
            raise NotSatisfiedWithData("Email address is needed in order to user this service and we could not get one from your social media provider. Please try to sign up with your email instead.")

**Comment by xunlao** [comment]
Has this been push to the Pypi?

**Comment by fairbairn** [comment]
Great solution, although many of the suggested fields have to be removed unless you've extended your minimal scope request (ie, address).  If you just use scope = ['email'], you'll want to trim it down a bit.

**Comment by miohtama** [comment]
The fixing change been pushed to PyPi and should be closed. I can confirm Authomatic works with Facebook out of the box again.
