### ISSUE TITLE
Request is done using gunicorn internal ip+port

### ISSUE THREAD

**Issue by lucianopuccio** [authomatic/authomatic#113]
I have django running under gunicorn + nginx. 
The request to facebook is done using the gunicorn ip+port instead of the main domain. For example http://45.55.111.111:8002/social_auth/login/fb instead of http://domain.com/social_auth/login/fb
I have properly configured the "Valid OAuth redirect URIs" from the facebook app to the appropiate url.
What happens afterwards is the user seems to be logged in correctly but is redirected to the gunicorn port and not to the main domain and port 80, from there, I cannot seem to redirect the user to the correct domain and port without losing the authentication.

Any thoughts? thanks in advance!

**Comment by jensens** [comment]
looks more like a configuration problem. i close this, please reopen if this is still a problem.
