### ISSUE TITLE
Login Yahoo failed

### ISSUE THREAD

**Issue by theking-laptop** [authomatic/authomatic#114]
@peterhudec 
I get this error when login via Yahoo:

```
Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.
```

But the special point is some Yahoo nicks log OK, but some failed. In case log OK, I can't find email in response information.

**Comment by mrichar1** [comment]
Apologies for the delay in responding.

Since this issue is now quite old, and there's not much debugging info to go on, I'm going to close this one.

If you are still experiencing this issue, please submit a new issue, with more debugging info, and we'll investigate further.
