### ISSUE TITLE
UnicodeEncodeError on cyrillic domain name

### ISSUE THREAD

**Issue by vadimtsabutashvili** [authomatic/authomatic#116]
Hi, I moved my app working on a cyrillic domain name http://www.xn----8sbbqjfeojqdl0beqo8c4ftc.xn--80asehdb/ and during login session I'm getting [this](http://pastebin.com/M8TtGskA) error. I'm using # coding=utf-8 but that doesn't help. Anything I can do about it? Thanks!

**Comment by mrichar1** [comment]
Unfortunately the pastebin of errors associated with this issue is now gone.  There have been a number of commits since the issue was raised that fix unicode errors, so this issue may have been resolved.

If you are still seeing this issue please open a new issue and we'll investigate.
