### ISSUE TITLE
Error when importing Webapp2Session

### ISSUE THREAD

**Issue by OpaVote** [authomatic/authomatic#117]
Hello, 

Doing this import:

```
from authomatic.extras.gae import Webapp2Session
```

causes this error:

```
File ".../views.py", line 11, in <module>
  from authomatic.extras.gae import Webapp2Session
File ".../authomatic/extras/gae/__init__.py", line 18, in <module>
  from authomatic.providers import openid
File ".../authomatic/providers/openid.py", line 29, in <module>
  from openid import oidutil
ImportError: No module named openid
```

The part causing the error isn't needed for `Webapp2Session` so I can get around the error by deleting a bunch of stuff in `authomatic/extras/gae/__init__.py`.

Is the `Webapp2Session` code tested?  Makes me nervous to use it if just the import fails.

**Comment by mrichar1** [comment]
openid providers rely on the 3rd-party `python-openid` package.  There's a warning at the top of the docs which highlights this: https://authomatic.github.io/authomatic/reference/providers.html#openid-providers
