### ISSUE TITLE
Facebook API - Cannot access anything other than ID, Name and Photo

### ISSUE THREAD

**Issue by emreozen** [authomatic/authomatic#132]
Anyone else having a similar problem? Thanks!

This is my config

```
'fb': {

    'class_': oauth2.Facebook,
    'consumer_key': '##################',
    'consumer_secret': '##################',
    'id':authomatic.provider_id(),
    'scope': ['user_about_me', 'email'],
},
```

**Comment by fairbairn** [comment]
Yes!  Guessing it depends on the API version your App is allowed to use.  Once it gets into 2.4 or 2.5, it doesn't get returned by default.  I think we may have to request the additional information using a fields query option.

**Comment by jensens** [comment]
see also  #132
