### ISSUE TITLE
Twitter Authentication - Access to email property

### ISSUE THREAD

**Issue by waxisien** [authomatic/authomatic#140]
We are now able to get user's email for twitter authentication : http://stackoverflow.com/questions/22627083/can-we-get-email-id-from-twitter-oauth-api

It would be nice to update the Twitter provider class, that way a user.update() call would get the email.
The user_info_url has to be changed to : 
https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true

**Comment by 1mh0** [comment]
Before you create `Config` dictionary, add this:
```python
# workaround to get user email for Facebook and Twitter API
oauth1.Twitter.user_info_url = 'https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true'
oauth2.Facebook.user_info_url = 'https://graph.facebook.com/v2.9/me?fields=id,first_name,last_name,email'

CONFIG = {    
    'tw': {
        'class_': oauth1.Twitter,
```
