### ISSUE TITLE
Twitter Failed 401

### ISSUE THREAD

**Issue by caoimhghin** [authomatic/authomatic#151]
Failed to obtain OAuth 1.0a oauth_token from https://api.twitter.com/oauth/access_token! HTTP status code: 401.

I'm not sure what is causing it. The app seems all setup correctly, are there any common issues that cause this?

Thanks!

**Comment by caoimhghin** [comment]
This was caused by the deprecated REQUESTS in Django... solved with returning the following from params instead.
```
a = self.request.POST.copy()
a.update(self.request.GET)
return(a.dict())
```

**Comment by jensens** [comment]
see also #149
