### ISSUE TITLE
AttributeError: 'LoginResult' object has no attribute 'js_callback'

### ISSUE THREAD

**Issue by matlac** [authomatic/authomatic#159]
I have following error while I'm trying to use "js_callback" as is described in documentation. User is redirecting to login page, and after return I got error caused by:
`AttributeError: 'LoginResult' object has no attribute 'js_callback'`

My code:
```
result = authomatic.login(WebObAdapter(request, response), provider_name)
    if result:
        if result.user:
             result.user.update()
        print(type(result)) # prints <class 'authomatic.core.LoginResult'>
        response.write(result.js_callback())
```

I'm using Pyramid 1.8.3, and Python 3.5.1

**Comment by mrichar1** [comment]
It looks like the documentation is out of sync here:

dac96293268f8166384ab188c20b63952a9dc06c `The LoginResult.js_callback() method renamed to LoginResult.popup_html()`

The methods are documented here correctly: https://authomatic.github.io/authomatic/reference/classes.html#authomatic.core.LoginResult

Hopefully this is enough to let you work around the incorrect docs, and we'll see about updating the documentation to reflect the actual code.
