### ISSUE TITLE
http NTLM proxy support?

### ISSUE THREAD

**Issue by segalion** [authomatic/authomatic#161]
Hello.
I would like to know if this authomatic code has easy support for NTLM auth http proxy.

I have been trying with flask-oauth, but seem very dificult for me how to make work the library with the ntlm proxy auth stuff.

There are millions of users inside ntlm proxies (general big companies with microsoft proxies) around the world, that need ntlm http-proxy auth.

I would like to know if microsoft graph (O365) is supported?

Thanks.

**Comment by mrichar1** [comment]
We don't currently offer NTLM proxy support.

Ideally this would be provided by the underlying http library we are using. `http.client` doesn't offer this, and neither do others we might consider using (https://github.com/requests/requests/issues/1582 and https://github.com/requests/requests/issues/1582).

Going to close this issue for now - we have considered moving to requests at some point in the future, and this will be looked into again then.
