### ISSUE TITLE
Need to make a release?

### ISSUE THREAD

**Issue by mrichar1** [authomatic/authomatic#192]
Hi,

After our push to get authomatic going again last year, it's fallen a bit by the wayside.
We made significant headway in improving the code and merging in PRs to deal with bugs and some new features - however we never got round to actually making a new release - in part due to the issues with the test suite not passing (from what I remember due to browser/client 'end to end' testing rather than the python unit tests).

I'd like to see a tagged release made, and pushed to pypi, so that what most people will consume is at least in better shape than the 0.1.0 release, which is broken for several significant use cases.

I think this would need @peterhudec to either make the push to pypi, or update `.travis.yml` with an appropriate key to trigger updates from future tagged commits. I also don't know how https://authomatic-example.appspot.com/ is updated.

Any thoughts?

**Comment by jensens** [comment]
Yes, indeed, we need a release! 

I usually use [zest.releaser](https://zestreleaser.readthedocs.io/en/latest/) for this task. But using TravisCI and automate things sound good too. In any case I'd prefer to get permissions on PyPI.

I also have no idea how to update the example app at GAE.

**Comment by cekk** [comment]
any news about this issue?

**Comment by ergo** [comment]
Bump. I also tried running some tests locally recently but I think the instructions are outdated.
I wanted to update pyramid example as it is way too complex and really written in a way that does not resemble how people work with the framework.

**Comment by jensens** [comment]
see #202

**Comment by mrichar1** [comment]
Release made: `1.0.0` - see #203 for details.
