### ISSUE TITLE
Update changes

### ISSUE THREAD

**Issue by fmigneault** [authomatic/authomatic#230]
First of all, thank you @jensens for integrating https://github.com/authomatic/authomatic/pull/195!

Is it possible to have an update/summary of what changed between https://github.com/authomatic/authomatic/releases/tag/1.0.0 and https://github.com/authomatic/authomatic/releases/tag/1.2.1?

The information is missing from https://github.com/authomatic/authomatic/blob/master/CHANGES.rst
I want to make sure I don't break something in the code using this library before updating everything.

**Comment by mrichar1** [comment]
Hi - yes this has been flagged in #225 for fixing. I'll add some basic notes there on what has changed, which we'll manually merge into CHANGES and then get the automated updates working again.

Will close this issue, but please lave any extra comments or questions on #225
