### ISSUE TITLE
`TypeError` on `HTTPSConnection.__init__()` on `authomatic/providers/__init__.py` row 456

### ISSUE THREAD

**Issue by cstrap** [authomatic/authomatic#235]
Authomatic 1.3.0 doesn't work on Python 3.12 due to `cert_file` parameter missing (deprecated on 3.11 and removed in 3.12)

Python docs `http.client.HTTPSConnection`:

- https://docs.python.org/3.11/library/http.client.html#http.client.HTTPSConnection
- https://docs.python.org/3.12/library/http.client.html#http.client.HTTPSConnection

It's not a `six` package problem, `six` fixes the namespace and not the `HTTPSConnection` object itself.

**Comment by Kirkman** [comment]
Looks like the problem is in lines 453-460 of [providers/__init__.py](https://github.com/authomatic/authomatic/blob/3fb3e06fd2a4a1618088a467c864a617bce51a9f/authomatic/providers/__init__.py#L453-L460).

Currently the code is:
```
        if url_parsed.scheme.lower() == 'https':
            context = None if ssl_verify else ssl._create_unverified_context()
            cert_file = certificate_file if ssl_verify else None
            connection = http_client.HTTPSConnection(
                url_parsed.hostname,
                port=url_parsed.port,
                cert_file=cert_file,
                context=context)
```

I think it needs to change to something like this:
```
        if url_parsed.scheme.lower() == 'https':
            if ssl_verify:
                context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=certificate_file)
            else:
                context = ssl._create_unverified_context()

            connection = http_client.HTTPSConnection(
                url_parsed.hostname,
                port=url_parsed.port,
                context=context)
```

**Comment by mrichar1** [comment]
Thanks for spotting this and suggesting a fix. I've implemented this in a PR and tests are passing (though feel free to try it out and feed back to the PR too!) and will look to get  new release of `authomatic` made soon.
