### ISSUE TITLE
Using travis for continuous testing

### ISSUE THREAD

**Issue by touilleMan** [authomatic/authomatic#68]
Hi,

Given the number of service providers authomatic can work with, it really complicated for a single person to do extensive testing.

Travis can encrypt data you want to put in your .travis.yml but still keep it private (e.g. password/tokens, see http://docs.travis-ci.com/user/encryption-keys/), you could create a bunch of test client/providers (I guess you already did ^^) and run the functional in the cloud them without exposing any credentials.

**Comment by mrichar1** [comment]
Now implemented in Travis testing.
