### ISSUE TITLE
Docs for config wrong - short_name instead of id

### ISSUE THREAD

**Issue by kavika13** [authomatic/authomatic#78]
On [http://peterhudec.github.io/authomatic/reference/config.html](the documentation page for provider config settings) it says to build the config (vaguely) like this:

```
'linked_in': {
     'class_': oauth2.LinkedIn,
     'short_name': 1,
     ...
},
```

The problem is that when I do this and call `response.user.to_dict()` it throws an error:

> To serialize credentials you need to specify a unique integer under the "id" key in the config for each provider!

To fix this I had to change the config to this:

```
'linked_in': {
     'class_': oauth2.LinkedIn,
     'id': 1,
     ...
},
```

I'm guessing the code got out of sync with the docs, though I might be using it wrong (?).

**Comment by mrichar1** [comment]
Thanks for pointing this out!

It looks like the linkedin config example has subsequently been removed from the docs - however the LinkedIn provider docs show the correct attributes, so will mark this closed. (https://authomatic.github.io/authomatic/reference/providers.html#authomatic.providers.oauth2.LinkedIn)
