### ISSUE TITLE
how to configure the google plus in simple django example for authomatic 

### ISSUE THREAD

**Issue by uayyappa** [authomatic/authomatic#83]
Hi Peter Hudec,
i had requirement to use oauth2 in my app. i seen lot of django configured source to connect with oauth. i liked your source very much because with simple configuration i completed it.but, i want connect using google along with facebook,twitter.fb & tw are working fine.so , will u help me how to configure the google in config.py of simple django example

**Comment by jensens** [comment]
enable g+ api under google configuration for apis
