### ISSUE TITLE
Facebook API  publish_stream

### ISSUE THREAD

**Issue by cescoferraro** [authomatic/authomatic#99]
Since yesterday, I have started to get this error

```
Invalid Scopes: publish_stream. This message is only shown to developers. Users of your app will   ignore these permissions if present. Please read the documentation for valid permissions at:    https://developers.facebook.com/docs/facebook-login/permissions
```

so I entered the developers.facebook.com to see what was going on. At first I thought because my fb app has not been reviewed yet plus the Graph API v1.0 Deprecation something I was wrong with my code. But the GAE Authomatic showcase is presenting the same issue [ Can not get the last statuses and neither can see the profile picture nor post]. I am still able to get the basic information but I have had to remove the publish_stream part from my config file, that I copied from the GAE showcase like below.

`'scope': oauth2.Facebook.user_info_scope +  ['publish_stream'],`

**Comment by jensens** [comment]
still an issue? if yes please reopen.
